#Stage 1: build

FROM maven:3.9.4-eclipse-temurin-17 AS build

# Update package lists and upgrade installed packages

RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/* 

# Set the working directory

WORKDIR /app

# Copy the package files

COPY . .

# Install the dependencies

RUN mvn clean package -DskipTests 

# Stage2: Runtime

FROM  eclipse-temurin:17-jre-alpine 

# Update package lists and upgrade installed packages

RUN apk update && apk upgrade && rm -rf /var/cache/apk/*

# Set the working directory

WORKDIR /app

# Copy the package files

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar" ]
