name: Backend Code Quality and Dependency Check

on: workflow_dispatch

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup Maven & Java
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 21
          java-distribution: temurin
          maven-version: 3.8.7
          cache: maven
          cache-dependency-path: backend/pom.xml

      - name: Resolve Maven dependencies
        working-directory: backend
        run: mvn dependency:go-offline dependency:resolve-plugins

      # Scan the raw filesystem before wasting compute on building if major vulnerabilities exist
      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          version: "v0.74.0"
          scan-type: "fs"
          scan-ref: "backend"
          severity: "HIGH,CRITICAL"
          exit-code: "1" # Change to "1" if you want to break the build on high/critical bugs

      - name: Maven Build & Verify
        working-directory: ./backend
        run: |
          mvn clean verify -DskipTests
          echo "Successfully compiled and verified the build."
