name: deploy to production server to EC2

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: ssh to prod server and create app folder
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Updating server... and Installing Docker..."
            sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
            sudo usermod -aG docker $USER || true
            sudo systemctl enable docker
            sudo systemctl start docker
            mkdir -p ~/devops
            echo "EC2 preparation completed"

      - name: Copy docker-compose file to prod server
        uses: appleboy/scp-action@v1.2.5
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: docker-compose.prod.yml
          target: ~/devops

      - name: Create production environment
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

          script: |
            set -e

            cat > ~/devops/.env <<EOF
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            IMAGE_TAG=latest
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}

            JWT_SECRET=${{ secrets.JWT_SECRET }}

            SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}

            CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}
            CORS_ALLOWED_METHODS=${{ vars.CORS_ALLOWED_METHODS }}
            CORS_ALLOWED_HEADERS=${{ vars.CORS_ALLOWED_HEADERS }}

            SPRING_PROFILES_ACTIVE=${{ vars.SPRING_PROFILES_ACTIVE }}
            SERVER_PORT=${{ vars.SERVER_PORT }}
            REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}
            EOF

            echo "Production environment created"

      - name: ssh to prod server and run the application
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/devops
            echo "Logging in to Docker Hub..."
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}"" --password-stdin

            echo "Pulling latest images..."
            docker compose -f docker-compose.prod.yml pull

            echo "Starting application..."
            docker compose -f docker-compose.prod.yml up -d --no-build --force-recreate --remove-orphans

            echo "Application status..."
            docker compose -f docker-compose.prod.yml ps
