name: Code Quality and dependency Check

on: workflow_dispatch

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      - name: Setup Nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependency
        working-directory: frontend
        run: |
          npm ci
          echo "Dependency Install successful"

      - name: Code Linting
        working-directory: frontend
        run: npm run lint

      - name: Dependency Security Check
        working-directory: frontend
        run: npm audit

      - name: Testing
        working-directory: frontend
        run: CI=true npm test -- --watchAll=false

      - name: Production Build
        working-directory: frontend
        run: CI=true npm run build
